### ISSUE TITLE
Can't run test suite

### ISSUE THREAD

**Issue by danwagnerco** [emirozer/bowshock#1]
Cool project!

I wanted to kick the tires a bit, but I'm having a really hard time running the test suite. With Python 3.4.1 (via Anaconda) on Windows 8.1, I get an `ImportError` on the `helpers` module.

![image](https://cloud.githubusercontent.com/assets/6598675/7548707/976ae88a-f5db-11e4-8c4d-e3403c9ccd90.png)

Figured I was being dumb or it was a Windows problem, so I spun up Vagrant's Precise32 box (Python 2.7.3) to give it a whirl. Unfortunately, that blamed `bowshock`.

![image](https://cloud.githubusercontent.com/assets/6598675/7548725/371c7ccc-f5dc-11e4-8877-1c08e1604fe0.png)

Can you tell what I'm doing wrong?

Thanks!
Dan

**Comment by emirozer** [comment]
Hi Dan,

Thanks for reporting this, i believe i know what the problem is, will check it and report back here..

**Comment by danwagnerco** [comment]
Fixed by #3
